# action.yaml
name: 'BotCity Actions - Bots'
description: 'Deploy, update and release bots to BotCity Maestro'
inputs:
  botId:
    description: 'Bot Id'
    required: true
  update:
    description: 'Is update?'
    required: false
    default: false
  deploy:
    description: 'Is deploy?'
    required: false
    default: false
  release:
    description: 'Is release?'
    required: false
    default: false
  version:
    description: 'Version number?'
    required: false
    default: ""
  technology:
      description: 'Technology?'
      required: true
  botPath:
    description: 'Path to compress bot?'
    required: true

branding:
  icon: 'settings'
  color: 'orange'

runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - name: Run botcity action
      id: botcity-action
      run: python ${{ github.action_path }}/main.py --update=${{ inputs.update }} --deploy=${{ inputs.deploy }}  --release=${{ inputs.release }} --version=${{ inputs.version }} --botId=${{ inputs.botId }} --path=${{ github.workspace }} --botPath=${{ inputs.botPath }} --technology=${{ inputs.technology }} --actionPath=${{ github.action_path }}
      shell: bash
