name: ci

on:
  push:
  pull_request_target:
  pull_request:

jobs:
  ci:
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Test Dependencies
        run: |
          pip install -r test-requirements.txt
          pip install -r requirements.txt
      - name: Run Tests
        env:
          SERVER: ${{ secrets.SERVER }}
          LOGIN: ${{ secrets.LOGIN }}
          KEY: ${{ secrets.KEY }}
        run: |
          pytest -v -vrxs
