name: ci

on:
  push:
    branches:
      - main
  pull_request_target:

env:
  SERVER: ${{ secrets.SERVER }}
  LOGIN: ${{ secrets.LOGIN }}
  KEY: ${{ secrets.KEY }}

jobs:
  # The authorize job is used to authorize external contributors to run tests
  # on the repository. This is necessary because the repository secrets are
  # not available to external contributors.
  # Source: https://iterative.ai/blog/testing-external-contributions-using-github-actions-secrets
  authorize:
    environment:
      ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository && 'external' || 'internal' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          true
  ci:
    needs: authorize
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Test Dependencies
        run: |
          pip install -r test-requirements.txt
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          pytest -v -vrxs
